// This is a placeholder URL. 
// You must replace this with the Web App URL generated by Google Apps Script.
const GAS_WEB_APP_URL = 'YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE';

export const recordTransaction = async (data) => {
    // If the URL is not set, just resolve to allow the UI to continue
    if (GAS_WEB_APP_URL.includes('YOUR_GOOGLE_APPS_SCRIPT')) {
        console.warn('Google Sheets API is not configured. Setup GAS_WEB_APP_URL in sheetApi.js');
        return new Promise(resolve => setTimeout(resolve, 800)); // fake delay
    }

    try {
        const response = await fetch(GAS_WEB_APP_URL, {
            method: 'POST',
            mode: 'no-cors', // standard way to send data to GAS without CORS issues
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(data)
        });
        
        // no-cors mode returns an opaque response, so we just assume success if no error was thrown
        return true;
    } catch (error) {
        console.error('Error recording transaction:', error);
        throw error;
    }
};
